### ISSUE TITLE
サイテーション

### ISSUE THREAD

**Issue by thangld201** [stockmarkteam/ner-wikipedia-dataset#3]
こんにちは @omitakahiroさん、データセットをリリースしていただき、誠にありがとうございます！
このデータセットを使用する場合、どのような引用が適切だと思いますか？

**Comment by omitakahiro** [comment]
@thangld201 ありがとうございます。下の文献を引用していただければと思います。可能であれば、このrepositoryへのリンク(https://github.com/stockmarkteam/ner-wikipedia-dataset) もつけていただけるとありがたいです。

近江崇宏、「Wikipediaを用いた日本語の固有表現抽出のデータセットの構築」、言語処理学会 第27回年次大会（2021）

PDF: https://anlp.jp/proceedings/annual_meeting/2021/pdf_dir/P2-7.pdf

**Comment by thangld201** [comment]
@omitakahiro ご返事ありがとうございました。 Latexにbibtexの形で引用する予定ですが、使っているlatexのテンプレートで日本語を書くのは難易度が高いので、以下の引用を英語にしました。もしおすすめがあれば、教えていただけると幸いです。
```
@misc{omitakahiro2021,
  author = {Takahiro Omi},
  title = {Building a Japanese named entity recognition dataset using Wikipedia},
  year = {2021},
  journal = {Proceedings of the Twenty-seventh Annual Meeting of the Association for Natural Language Processing},
  howpublished = {\url{https://github.com/stockmarkteam/ner-wikipedia-dataset}, \url{https://anlp.jp/proceedings/annual_meeting/2021/pdf_dir/P2-7.pdf}}
}
```

**Comment by omitakahiro** [comment]
@thangld201 ありがとうございます。私としては、そちらで異論はありません。
